examples/mistnetplus/mistnetplus_client.py
examples/split_learning/split_learning_algorithm.py
examples/split_learning/split_learning_client.py
examples/split_learning/split_learning_server.py
examples/split_learning/split_learning_trainer.py

Split learning update

---

examples/mistnetplus/mistnetplus_server.py
examples/mistnetplus/split_learning_algorithm.py
examples/split_learning/split_learning_algorithm.py
examples/split_learning/split_learning_server.py
plato/algorithms/mistnet.py
plato/datasources/feature.py
plato/datasources/registry.py
plato/servers/mistnet.py

Close #114. Add feature DataSource class. Modify all related servers to use this class for Sampler. Modify related algorithms to use this class for creating PyTorch Dataset for training.
Added a feature DataSource class, used by servers training with features received from clients. Feature DataSource object is supplied to Sampler and Algorithm.train(). Feature DataSource object also provides conversion to torch Dataset to replace and the three separate FeatureDataset used in algorithms.
Solves issue #114. Sampler objects always require Datasource object as its parameter, not a list.
Error in #114 is not reproduced.

Providing feature DataSource object to Sampler in MistNet server and similar.

---

.github/workflows/plato-test.yml
packages/yolov5/yolov5/data/hyps/hyp.finetune.yaml
packages/yolov5/yolov5/data/hyps/hyp.finetune_objects365.yaml
packages/yolov5/yolov5/data/hyps/hyp.scratch-high.yaml
packages/yolov5/yolov5/data/hyps/hyp.scratch-low.yaml
packages/yolov5/yolov5/data/hyps/hyp.scratch-med.yaml
packages/yolov5/yolov5/data/hyps/hyp.scratch.yaml
plato/trainers/yolo.py

This RP added CI tests for evaluating each commit. It currently supports LeNet and YOLO-v5.
I have fixed some bugs when running LeNet. 
Many bugs were produced in some commits. It is hard to debug without knowing which commit causes those bugs.
After submitting each commit, GitHub will automatically run some pre-defined commands to evaluate that commit to make sure the commit will not bring new bugs to the existing codes.
Submit a Commit to github.
- [*] Bug fix (non-breaking change which fixes an issue) Fixes #
- [*] New feature (non-breaking change which adds functionality)
- [*] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [*] My code follows the code style of this project.

Added github CI tests and fixed some bugs.

---

.github/workflows/pytorch_tests.yml

Fix unit test for PyTorch in GitHub action.
See unit test part of Pytorch pipeline in the GitHub action.

Fix unit test for PyTorch

---

.github/workflows/configs/mistnet_yolov5.yml
.github/workflows/pytorch_tests.yml
configs/Kinetics/kinetics_mm.yml
configs/MNIST/mistnet_lenet5.yml
configs/YOLO/mistnet_helmet.yml
configs/YOLO/mistnet_yolov5.yml
docs/Configuration.md
examples/nnrt/nnrt_algorithms/mistnet.py
plato/algorithms/mistnet.py
plato/clients/base.py
plato/clients/edge.py
plato/clients/mistnet.py
plato/clients/simple.py
plato/config.py
plato/processors/mistnet_random_response.py
plato/processors/registry.py
plato/servers/base.py
plato/servers/fedavg.py
tests/config_tests.py

Fixed various issues in the Processor class and revised the configuration file setup.
- Fixed a Python 3.6 incompatibility with the use of `typing.Literal`, which is only available in Python 3.8 and up.
- On both clients and the server, moved the code from set_processors() into configure() and made configure() a regular rather than an abstract method.
- revised the configuration setup, and added a test case for the new way of reading configuration files with multi-modal datasets.
- Revised the PyTorch CI tests to run unit tests outside `tests/`.
```shell
find tests -name '*.py' -exec python {} \;
./run --config=configs/MNIST/mistnet_lenet5.yml
./run --config=configs/MNIST/fedavg_lenet5.yml
```

Fixed various issues in the Processor class, revised the configuration setup, and added a test case for configurations

---

configs/MNIST/fedavg_lenet5.yml
docs/Configuration.md
plato/clients/simple.py
plato/processors/model_pruning.py
plato/processors/registry.py

Provide model pruning as data processor for PyTorch models.
Prune model with global unstructured pruning. Prune the weight of every linear and conv layer. Result of pruning can be saved back to the client model if the user choose to.

Model pruning

---

plato/servers/fedavg_cs.py

Fixed issue #142. 
Removed self.do_edge_test.
Tested with configs/MNIST/fedavg_cross_silo_lenet5.yml.

Fixed issue #142.

---

.github/workflows/pytorch_tests.yml
configs/MNIST/mistnet_lenet5.yml
plato/clients/base.py
plato/processors/compress.py
plato/processors/decompress.py
plato/processors/feature_randomized_response.py
plato/processors/feature_unbatch.py
plato/processors/registry.py
plato/servers/base.py
requirements.txt

A cooperation work with @TrackerLB 
1. Fixed the issue of transferring feature data in PyTorch tensor.
2. Fixed the order issue in feature_randomized_response.
3. Added compression support
See in MNIST + MistNet_lenet test yaml file.
The performance comparison: 
```
Before fixing Before fixing bugs
[INFO][13:50:26]: [Client #1] Sent 299.99 MB of payload data (before pickle) to the server.
[INFO][13:50:26]: [Client #1] Sent 311.22 MB of payload data to the server.
[INFO][13:34:29]: [Client #1] Sent 80.26 MB of payload data (before pickle) to the server.
[INFO][13:34:29]: [Client #1] Sent 92.67 MB of payload data to the server.
[INFO][14:52:34]: [Client #1] Sent 9.31 MB of payload data (before pickle) to the server.
[INFO][14:52:34]: [Client #1] Sent 14.08 MB of payload data to the server. …
```

Bugs fixed in processer classes and compression support in new processer class

---

plato/clients/base.py
plato/servers/base.py
plato/servers/fedavg_cs.py

This pull request fixes issues of using client simulation mode in cross-silo training.
This pull request corrects the edge client ids, and the client ids of each edge server in client simulation mode.
Tested with the configuration file configs/MNIST/fedavg_cross_silo_lenet5.yml.

Fixed issues of using client simulation mode in cross-silo training

---

docs/Configuration.md
examples/adaptive_hgb/adaptive_hgb_client.py
examples/fedasync/fedasync_server.py
examples/fedunlearning_baseline/fedunlearning_client.py
plato/clients/base.py
plato/clients/simple.py
plato/samplers/dirichlet.py
plato/samplers/iid.py
plato/servers/fedavg.py
plato/servers/mistnet.py

This PR fixed bugs in data samplers and changed the condition of clients testing locally
This PR fixed bugs in iid and dirichlet samplers, and changed the condition of clients testing locally so that it is not a must to have `clients.do_test` in a configuration file.
Printed out data samples of each selected clients in each communication round to make sure that each client has the same samples in every round but different clients have different samples.

General fix and update

---

examples/adaptive_freezing/adaptive_freezing_algorithm.py
examples/adaptive_hgb/adaptive_hgb_server.py
examples/adaptive_sync/adaptive_sync_algorithm.py
examples/afl/afl_server.py
examples/attack_adaptive/attack_adaptive_server.py
examples/fedadp/fedadp_server.py
examples/fedasync/fedasync_server.py
examples/fedatt/fedatt_server.py
examples/fednova/fednova_server.py
examples/fedreId/fedreId_server.py
examples/fedsarah/fedsarah_server.py
examples/fedsaw/fedsaw_client.py
examples/fedsaw/fedsaw_edge.py
examples/fedsaw/fedsaw_server.py
examples/fei/fei_server.py
examples/mistnetplus/mistnetplus_server.py
examples/port/port_server.py
examples/scaffold/scaffold_server.py
plato/algorithms/base.py
plato/algorithms/tensorflow/fedavg.py
plato/servers/fedavg.py
plato/utils/reinforcement_learning/rl_server.py
tests/fedavg_tests.py

In this refactoring PR, a number of variable names and function names have been refactored so that the term `updates` consistently mean what the clients sent to the server in each communication round, and `deltas` mean the difference between the model that the clients sent and the global model on the server.
The changes have been tested using `./run -c configs/MNIST/fedavg_lenet5.yml`. It would be best if it can be tested using other examples beyond the basic FedAvg.

Refactored code across-the-board so that `updates` mean what clients sent to the server and `deltas` mean model deltas

---

plato/servers/base.py
plato/trainers/basic.py

This PR fixed the record of elapsed time.
There was a bug of logging elapsed time due to training clients in batches. 
After each batch, the wall clock advances. So the elapsed time is longer than the actual. 
This PR fixed this problem.
Tested with ./run -c configs/MNIST/fedavg_lenet5.yml

Fixed logging of elapsed time

---

examples/basic/basic.py
examples/customized/custom_client.py
examples/customized/custom_server.py
plato/clients/simple.py
plato/servers/fedavg.py

Fixed the reported bug #184 presented as "Unable to define the custom model for client and server"
Just made slight changes to the function `load_trainer` of `plato/servers/fedavg.py` by instantiating the model 
I tested the revised code on the reported example `examples/base_siamese` in the bug #184 and on the previous example `examples/fedprox`

Fixed an issue in the server implementation when using customized models. Closes #184.

---

docs/Configuration.md
plato/samplers/sampler_utils.py
plato/trainers/diff_privacy.py

Rewrite Opacus `BatchMemoryManager` class to enable the batch_sampler in the original train_loader.
It has been tested.
1. Enable differential privacy in `configs/EMNIST/fedavg_lenet5.yml`
2. Execute `./run -c configs/EMNIST/fedavg_lenet5.yml `
3. Execute `./run -c configs/CIFAR10/fedavg_vgg16_dp.yml` 4.

Rewrite Opacus BatchMemoryManager to enable sampler.

---

plato/servers/base.py

This PR fixed issues in #195 
This PR fixed issues in #195 
Tested with the configuration file provided in #195

Fixed issue #195

---

examples/FedRep/fedrep_trainer.py
examples/adaptive_hgb/adaptive_hgb_trainer.py
examples/afl/afl_trainer.py
examples/fei/fei_trainer.py
examples/fl_maml/fl_maml_trainer.py
examples/mistnetplus/split_learning_trainer.py
examples/sub_fedavg/subfedavg_trainer.py
plato/trainers/basic.py
plato/trainers/diff_privacy.py

This PR fixed an issue computing iterations per epoch when using a learning rate schedule in the default training loop in the basic trainer.
```
./run -c configs/MNIST/fedavg_lenet5.yml
```

Corrected the computation of iterations per epoch

---

docs/Configuration.md
plato/servers/base.py

This PR added communication time computed by specified bandwidth when client-server communication is simulated with files.
In previous implementation, communication time is 0 when client-server communication is simulated with files. This PR provides the option of computing communication time with specified bandwidth.
Test with configs/MNIST/fedavg_lenet5.yml with adding `compute_comm_time: true` under `clients`.

Added communication time computed by specified bandwidth

---

examples/oort/oort.py
examples/oort/oort_MNIST_lenet5.yml
examples/oort/oort_client.py
examples/oort/oort_server.py
examples/oort/oort_trainer.py

This PR implemented the Oort algorithm.
Implemented the client selection algorithm described in "Oort: Efficient Federated Learning
via Guided Participant Selection"  by @kevinsun203.
Ran ```oort_MNIST_lenet5.yml``` in synchronous environment when per_round = max_concurrency and when per_round > max_concurrency.

Implemented Oort

---

examples/oort/oort.py
examples/oort/oort_MNIST_lenet5.yml
examples/oort/oort_client.py
examples/oort/oort_server.py
examples/oort/oort_trainer.py
packages/yolov5/yolov5/utils/loss.py
plato/processors/model_dequantize.py
plato/processors/model_quantize.py

request to merge main for most recent updates into branch

Branch merge request

---

docs/Configuration.md
plato/servers/base.py

This PR updated the computation of communication time.
Changed the unit of bandwidth from MBps to Mbps.
Changed the default value of bandwidth to 100 Mbps.
Changed the per-client uplink bandwidth to the server bandwidth divided by the minimum number of clients (in asynchronous mode) or number of clients per round (in synchronous mode).
Test with configs/MNIST/fedavg_lenet5.yml with adding `compute_comm_time: true` under clients.

Updated the computation of communication time

---

README.md
configs/CIFAR10/mistnet_resnet18.yml
docs/Configuration.md
examples/adaptive_sync/adaptive_sync_algorithm.py
examples/fedcm/fedcm.py
examples/fedcm/fedcm_algorithm.py
examples/fedcm/fedcm_cifar10_resnet18.yml
examples/fedcm/fedcm_client.py
examples/fedcm/fedcm_server.py
examples/fedcm/fedcm_trainer.py
packages/yolov5/yolov5/utils/loss.py
plato/samplers/dirichlet.py
plato/samplers/distribution_noniid.py
plato/samplers/mindspore/dirichlet.py
plato/samplers/orthogonal.py
plato/servers/base.py
plato/trainers/basic.py
plato/utils/optimizers.py

pull request to merge main into branch

pull request for merging

---

docs/configuration.md
docs/netlify.toml

This PR updated the documentation for configuration settings to the new documentation format and refreshed the content as well.

Updated the documentation for configuration settings.

---

docs/configuration.md
examples/FedRep/fedrep_CIFAR10_resnet18.yml
examples/FedRep/fedrep_CIFAR10_resnet18_label_quantity_nonIID.yml
examples/FedRep/fedrep_CIFAR10_vgg16.yml
examples/FedRep/fedrep_MNIST_lenet5.yml
examples/fednova/fednova_MNIST_lenet5.yml
examples/fedprox/fedprox_MNIST_lenet5.yml
examples/fedsarah/fedsarah_MNIST_lenet5.yml
examples/fedsaw/fedsaw_MNIST_lenet5.yml
examples/fedscr/fedscr_MNIST_lenet5.yml
examples/fedunlearning_baseline/fedun_MNIST_lenet5.yml
examples/fei/fei_FashionMNIST_lenet5.yml
examples/fl_maml/fl_maml_MNIST_lenet5.yml
examples/hermes/hermes_MNIST_lenet5.yml
examples/norm_bounding/norm_bounding_MNIST_lenet5.yml
examples/oort/oort_MNIST_lenet5.yml
examples/scaffold/scaffold_MNIST_lenet5.yml
examples/scaffold/scaffold_trainer.py
examples/sub_fedavg/subfedavg_MNIST_lenet5.yml
examples/sub_fedavg_cs/subcs_MNIST_lenet5.yml
examples/tempo/tempo_MNIST_lenet5.yml

The rest of the configuration files have been changed underneath plato/examples

revised the rest of the configuration files under plato/examples

---

docs/configuration.md
docs/patches/base.py.patch
plato/clients/base.py
plato/clients/edge.py
plato/clients/simple.py
plato/servers/base.py
plato/servers/fedavg_cs.py
plato/trainers/yolov5.py

This PR supports asynchronous cross-silo FL.
Fixed bugs in cross-silo FL.
Supported asynchronous cross-silo FL.
Updated patches for running on Compute Canada.
Tested with the configuration file configs/MNIST/fedavg_cross_silo_lenet5.yml.

Supported asynchronous cross-silo FL.

---

examples/FedRep/fedrep_server.py
examples/afl/afl_server.py
examples/customized/custom_server.py
examples/dlg/dlg_server.py
examples/fedadp/fedadp_server.py
examples/fedasync/fedasync_server.py
examples/fedreId/fedreId_server.py
examples/fedsarah/fedsarah_server.py
examples/fedscr/fedscr_server.py
examples/fedunlearning/fedunlearning_server.py
examples/fl_maml/fl_maml_server.py
examples/hermes/hermes_server.py
examples/mistnetplus/mistnetplus_server.py
examples/oort/oort_server.py
examples/scaffold/scaffold_server.py
examples/split_learning/split_learning_server.py
plato/servers/fedavg.py
plato/servers/fedavg_cs.py
plato/servers/mistnet.py
plato/utils/reinforcement_learning/rl_server.py

Fixed a bug that fedavg.Server doesn't take ```callbacks``` as a parameter, nor does it pass callbacks to base.Server, which prevents the usage of callbacks in fedavg.Server and its derived classes. 
The change has been tested by passing a customized printing callback to fedavg.Server.

Fixed a bug of using callbacks in fedavg.Server.

---

examples/oort/oort_server.py

In asynchronous model, Oort sever should exclude running clients when does client selection.
`python oort.py -c oort_MNIST_lenet5.ym `

Fixed a bug for Oort server.

---

plato/servers/base.py

When clients have same finish time, the server compares their id when does selection.
When clients have same finish time, the server compares their id when does selection.
`./run -c configs/MNIST/fedavg_lenet5.yml`

Fixed a bug in server/base.py.

---

docs/examples.md
examples/afl/afl_server.py
examples/knot/knot_server.py
examples/oort/oort_server.py
examples/pisces/pisces_server.py

Server should exclude running clients when does client selection.
`python examples/oort/oort.py -c oort_MNIST_lenet5.yml`

Fixed a bug of Oort server.

---

plato/models/torch_hub.py

Fixed a small bug that in models/torch_hub.py/get()/torch.hub.load, we forgot to add kwargs in the function parameters.

added kwargs into torch.hub.load

---

docs/examples.md
examples/fedbabu/fedavg_cifar10_levit.yml
examples/fedbabu/fedbabu.py
examples/fedbabu/fedbabu_trainer.py
examples/fedrep/fedrep.py
examples/fedrep/fedrep_CIFAR10_resnet18.yml
examples/fedrep/fedrep_CIFAR10_resnet18_label_quantity_nonIID.yml
examples/fedrep/fedrep_CIFAR10_vgg16.yml
examples/fedrep/fedrep_MNIST_lenet5.yml
examples/fedrep/fedrep_algorithm.py
examples/fedrep/fedrep_client.py
examples/fedrep/fedrep_server.py
examples/fedrep/fedrep_trainer.py

First, FedBABU algorithm is added into the examples. According to the paper, only the body part of the model is updated. As a result, in the implementation, first the head part of the model is frozen, and then the training begins. The core part is in ```fedbabu_trainer.py```, where ```freeze_model``` is added in the ```train_run_start``` to freeze the head part.
Second, FedRep is moved out of the folder outdated, that example can work with current plato API.
FedBABU and FedRep are two algorithms designed for personalized federated learning, both of them claim that they achieve state-of-the-art over other existing methods.
FedBABU run the command
```
python3 examples/fedbabu/fedbabu.py -c examples/fedbabu/fedavg_cifar10_levit.yml
```
FedRep run the command
```
python3 …
```

Example Code of implementing FedBABU and FedRep moved from outdated after testing

---

examples/fedunlearning/fedunlearning_client.py
plato/clients/base.py
plato/clients/simple.py

Fixed the data loading and sampling issues in base, simple, and fedunlearning clients
- Remove the useless if statement and reload datasource only when `reload_data` is set true in .yml files, e.g., for the pre-partitioned Federated EMNIST dataset.
- Split `_load_data()` function to `_load_data()` before `configuration()` and `_allocate_data()` after `configuration()` and move sampler assignment part into `configuration()` for better customization.
- Fix the sampler overriding issue in fedunlearning.

Fix sampling issue

---

examples/fedunlearning/fedunlearning_adahessian_MNIST_lenet5.yml
examples/fedunlearning/fedunlearning_client.py
examples/fedunlearning/fedunlearning_server.py
examples/fedunlearning/unlearning_iid.py
plato/utils/lib_mia/mia.py
plato/utils/lib_mia/mia_client.py
plato/utils/lib_mia/mia_server.py

- Implement FedEraser's MIA in plato/utils/lib_mia
- mia.py: `train_attack_model()` and `launch_attack()` fulfill the basic functions of MIA
- mia_server.py: a customized server based on `fedavg.server`, which calls MIA with passing it arguments needed
- mia_client.py: a customized client based on `simple.client`, which adds local sample indices in client's report for MIA
- Update Fedunlearning algorithm
- Improve unlearning_iid.py to also keep record of deleted data for sampling
- Make fedunlearning_server and fedunlearning_client inherited from mia_server and mia_client instead respectively to apply MIA
Run cmd `python examples/fedunlearning/fedunlearning.py -c examples/fedunlearning/fedunlearning_adahessian_MNIST_lenet5.yml`

Add implementation of MIA and update Fedunlearning to apply MIA
