plato/clients/simple.py, plato/trainers/base.py, plato/trainers/basic.py, plato/utils/decorators.py
This change moves the client's training time recording from method `train()` in plato/clients/simple.py to method `train()` in plato/trainers/basic.py. The point is that excluding the call of method `start_training()` from this elapsed time measure. 
The original way to measure client's training time in plato/clients/simple.py is incorrect as it also takes into account the corresponding trainer's waiting time for running, i.e. the process's sleep time in `start_training()` in plato/trainers/base.py.
Before the change, for example, if `max_concurrency` is set to `1` in the configuration file which means the maximum number of clients running concurrently is one, the recorded training time of all clients in each communication round is like:
where the training time is extracted from the …
=> Correct the measure of client training time

docs/Configuration.md, plato/clients/edge.py, plato/clients/simple.py, plato/samplers/all_inclusive.py, plato/samplers/dirichlet.py, plato/samplers/iid.py, plato/samplers/mixed.py, plato/samplers/orthogonal.py, plato/samplers/registry.py, plato/servers/fedavg_cs.py, plato/trainers/basic.py
Use configuration parameter `test_set_sampler` under `data` to specify the sampler of clients' test sets . Without this parameter, clients' test sets will be the test set of datasource.
All classes of Sampler take an additional parameter `testing`. If `testing` is true, it means that this sampler is for generating test set; otherwise it is for generating training set.
Tested iid, dirichlet, all_inclusive, mixed and orthogonal samplers under both two-layer and three-layer FL.
=> Added sampler for testset.

configs/MNIST/fedavg_async_lenet5.yml, examples/cs_maml/cs_maml_server.py, examples/fl_maml/fl_maml_server.py, examples/mistnetplus/mistnetplus_server.py, examples/split_learning/split_learning_server.py, plato/clients/base.py, plato/servers/base.py, plato/utils/rlfl/simple_rl_server.py
This PR adds basic support for bounded staleness in asynchronous mode in Plato.
The algorithm that is currently implemented can be described as follows:
Assuming that in a federated learning session, staleness is 2.
When a server sends out a model to a newly selected client, it will:
(1) Record the current communication round index for this client, indicating that this client is currently working in this communication round.
(2) Send out the current model.
When a server received a model update from a client it has previously selected, it will:
(1) "save" the model update for this reporting client;
(2) If the slowest client is at least working in round #(current communication round index - 2), aggregate all the model updates received so far, and then select a new client to replace this …
=> Added basic support for bounded staleness in async mode.

plato/datasources/feature.py
The class `DataSource` in file **plato/datasources/feature.py** does not implement method `__len__()` and `__getitem__()`, which causes the program to raise a TypeError when running the split learning example. The change fixes the bug by implementing these two methods.
This commit aims to resolve issue #140 
The change is tested by executing file **examples/split_learning/split_learning.py** and no errors were raised. The program successfully finished the training.
=> Update feature.py to fix a TypeError bug of split learning example

examples/afl/afl_client.py, examples/fedasync/fedasync.py, plato/config.py
An AttributeError could be raised if the user wants to save results by adding the `results` section in the configuration .yml file but does not provide `results_dir` and `type` for `algorithm`
Currently, if the user adds a `results` section in the .yml config file but does not give a`results_dir` attribute, the program will create a default result directory of `./results/{datasource}/{model}/{server_type}/`, where `server_type` is assigned to be the `type` of `algorithm`. However, if the user wishes to implement their own algorithm, they might not provide a type to the algorithm in the config file, and that would give an AttributeError since the program could not find the `type` attribute of the algorithm.
The fix simply sets `server_type` to a default value and re-assigns the variable to …
=> Fix an issue with the naming of directory to store result .csv files

examples/axiothea/axiothea_client.py, examples/fedsarah/fedsarah_client.py
Change the attribute of class `Report` used by examples correctly to adapt the change in `simple.Report`
The dataclass `simple.Report` in `clients/simple.py` has been updated to include only one attribute `update_response`, but this change has not been propagated to examples that use this class. They are still using `report.data_loading_time`.
The fix updates the attribute used by example `fedsarah` and `axiothea` correctly.
Run `examples/fedsarah/fedsarah.py` without error.
=> Update Report class in examples to adapt the change in simple.Report

examples/cs_maml/cs_maml_trainer.py, examples/fedasync/fedasync_CIFAR10_resnet18.yml, examples/fedasync/fedasync_MNIST_lenet5.yml, examples/fedasync/fedasync_server.py, examples/fednova/fednova_client.py, examples/fl_maml/fl_maml_trainer.py, plato/config.py
Add new YML file for FedAsync example to reproduce the CIFAR10 experiment in the original paper
Add new file `fedasync_CIFAR10_resnet18.yml` under `examples/fedasync` that tries to reproduce the experiment with CIFAR10 dataset in the original FedAsync paper.
Also update `fedasync_server.py` to support the use of different staleness weighting functions mentioned in the paper when updating the mixing hyperparameter
Execute the following command with no error:
`python run.py --config=examples/fedasync/fedasync_CIFAR10_resnet18.yml`
1. The original paper uses its own custom convolutional neural network to run the experiments, which I'm not so sure how to reproduce in the Plato framework, so I just use the existing ResNet18 model.
2. The original paper also simulates the staleness of clients …
=> Add new config file for FedAsync example to reproduce the experiment in the original paper

examples/fedprox/fedprox.py, examples/fedprox/fedprox_MNIST_lenet5.yml, examples/fedprox/fedprox_trainer.py, plato/trainers/basic.py
This pull request tries to implement the FedProx framework proposed in this paper: https://proceedings.mlsys.org/paper/2020/file/38af86134b65d0f10fe33d30dd76442e-Paper.pdf
FedProx is a synchronous federated learning framework that is very similar to FedAvg except that FedProx adds a proximal term to the local objective that clients wish to minimize (i.e. the training loss function of the client). In other words, a FedProx client will train to minimize the following objective:
where <img src="https://render.githubusercontent.com/render/math?math=F_k(w)"> is the original loss function of clients in FedAvg, <img src="https://render.githubusercontent.com/render/math?math=w"> is the weight of the client model in the current training epoch, <img …
=> Add implementation of Fedprox example

configs/EMNIST/fedavg_lenet5.yml, configs/MNIST/fedavg_async_lenet5.yml, configs/MNIST/fedavg_lenet5.yml, examples/adaptive_hgb/adaptive_hgb_server.py, examples/afl/afl_server.py, examples/cs_maml/cs_maml_server.py, examples/fedadp/fedadp_server.py, examples/fednova/fednova_server.py, examples/fedsaw/fedsaw_server.py, examples/fei/fei_server.py, examples/fl_maml/fl_maml_server.py, examples/port/port_server.py, examples/sub_fedavg_cs/subcs_server.py, plato/servers/base.py, plato/servers/fedavg.py, plato/servers/fedavg_cs.py, plato/utils/csv_processor.py, plato/utils/reinforcement_learning/rl_server.py
When running a job, if the configuration file has the attribute "do_test" set to true and if there also exists a "results" attribute, then the test accuracies of each client will be computed locally and stored in a csv file with the round number, client ID and test accuracy as headers.
Tested on local machine using the "fedavg_async_lenet5" configuration file  with 1-3 clients. Each with 1-3 rounds after setting "do_test" to True and another time to False
=> Added the facility to record local testing accuracies in .csv files

plato/servers/fedavg.py, plato/servers/fedavg_cs.py
This PR made the recording of customized items easier.
To record customized items on a custom server more easily, this PR separated the original wrap_up_processing_reports() function. With this PR, if one wants to record additional items that are not in get_record_items_values() of /plato/server/fedavg.py, it is only needed to add them in its inherited get_record_items_values() function, instead of overriding the whole wrap_up_processing_reports() function.
Tested with ./run -c configs/MNIST/fedavg_lenet5.yml
and ./run -c configs/MNIST/fedavg_cross_silo_lenet5.yml
=> Recorded customized items more easily

examples/cs_maml/cs_maml_server.py, examples/fl_maml/fl_maml_server.py, plato/servers/base.py
This PR fixed an issue in async FL when two or more clients have the same finish time.
In previous implementation of async FL, if two or more clients have the same earliest finish time, it will give 
TypeError: '<' not supported between instances of 'dict' and 'dict'
when heappop the client with the earliest finish time.
This PR fixed this issue by adding a field of a random number between the finish time and the dict in client_info.
Tested with [configs/EMNIST//fedavg_async_lenet5.yml](https://github.com/TL-System/plato/blob/main/configs/EMNIST/fedavg_async_lenet5.yml)
=> Fixed an issue in async FL

examples/basic/basic.py, examples/fedunlearning_baseline/fedunlearning_client.py, plato/clients/simple.py, plato/trainers/basic.py, plato/trainers/mindspore/basic.py, plato/trainers/tensorflow/basic.py
Corrected the customized model initialization in the trainer `__init__` and update the model in basic/basic.py to make it compatible with this change.
The custom model should be passed as a class in the starting program and then initialized as an instance in trainer `__init__` by `self.model = model.get_model()`, otherwise the server and clients will share the same model object.
Any custom model should have the method `get_model()` implemented for obtaining an instance of it in the trainer. For example, the method should be like the followings:
```
@staticmethod
def get_model(*args):
"""Obtaining an instance of this model."""
return Model()
```
or
```
@staticmethod
def get_model(*args):
"""Obtaining an instance of this model."""
if hasattr(Config().trainer, 'num_classes'):
return …
```
=> Correct the customized model in trainer as an object

docs/Design.md, examples/FedRep/fedrep_server.py, examples/basic/basic.py, examples/catalyst/catalyst_example.py, examples/customized/custom_client.py, examples/fedreId/fedreId_client.py, examples/nnrt/nnrt.py, plato/clients/simple.py, plato/servers/fedavg.py, plato/servers/fedavg_cs.py, plato/servers/mistnet.py, plato/utils/reinforcement_learning/rl_server.py, tests/fedavg_tests.py
This PR supports the use of a custom datasource on the FL server, and modified related examples that uses custom models and datasources to be compatible with the latest changes of passing classes rather than instances into Plato.
```
python examples/basic/basic.py -c configs/MNIST/fedavg_lenet5.yml
```
=> Supported a custom datasource on the server

plato/trainers/basic.py, plato/utils/optimizers.py
The learning rate schedulers: ChainedScheduler, SequentialLR, MultiStepLR, StepLR, ConstantLR, LinearLR, ExponentialLR, CyclicLR, and CosineAnnealingWarmRestarts were added into plato/utils/optimizers.py according to the documentation found at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate.
To use the different schedulers, the "lr_schedule" would be set equal to any of the schedulers above as usual. In the case of ChainedScheduler and SequentialLR which calls other schedulers, "lr_schedule" would be set equal to a comma-separated list of required schedulers along with either ChainedScheduler or SequentialLR.
This was tested by running ```./run -c configs/CIFAR10/fedavg_resnet18.yml``` using each newly added scheduler once.
=> Added the remaining learning rate schedulers found in PyTorch

.github/workflows/mindspore_tests.yml, Dockerfile_MindSpore, docs/configuration.md, docs/patches/base.py.patch, docs/patches/config.py.patch, docs/patches/patch_cc.sh, docs/quickstart.md, examples/adaptive_hgb/adaptive_hgb_client.py, examples/fedreId/fedreId_client.py, examples/fedsaw/fedsaw_MNIST_lenet5.yml, examples/mistnetplus/mistnetplus_client.py, examples/split_learning/split_learning_client.py, examples/sub_fedavg_cs/subcs_MNIST_lenet5.yml, plato/clients/mistnet.py, plato/clients/simple.py, plato/samplers/all_inclusive.py, plato/samplers/base.py, plato/samplers/dirichlet.py, plato/samplers/distribution_noniid.py, plato/samplers/iid.py, plato/samplers/label_quantity_noniid.py, plato/samplers/mindspore/dirichlet.py, plato/samplers/mindspore/iid.py, plato/samplers/mixed_label_quantity_noniid.py, plato/samplers/orthogonal.py, plato/samplers/registry.py, plato/samplers/sample_quantity_noniid.py, plato/samplers/tensorflow/base.py, plato/servers/fedavg.py, plato/servers/fedavg_cs.py
Refactored the design of the `all_inclusive` sampler so that an optional `data -> testset_size` can be used to determine the number of samples to draw from a `SubsetRandomSampler`. By default, the `all_inclusive` sampler will draw from all the samples in the train or test dataset.
This refactoring also fixed a runtime error when the server specifies the `testset_size`.
=> Refactored the design of the all_inclusive sampler.

docs/client.md, examples/FedRep/fedrep_client.py, examples/adaptive_hgb/adaptive_hgb_client.py, examples/customized_processor/customize_callback.py, examples/customized_processor/customize_processor.py, examples/customized_processor/dummy_processor.py, examples/fedsarah/fedsarah_client.py, examples/fedunlearning/fedunlearning_client.py, examples/fl_maml/fl_maml_client.py, examples/scaffold/scaffold_client.py, examples/split_learning/split_learning_client.py, plato/callbacks/client.py, plato/clients/base.py, plato/clients/edge.py, plato/clients/simple.py, plato/processors/base.py, plato/processors/registry.py
Added client callbacks before the inbound and outbound processors start to process the data, which allows user to dynamically adjusting the processor lists or settings in the runtime.
The new feature has been tested by running ```python examples/customized_processor/customize_processor.py -c configs/MNIST/fedavg_lenet5.yml```, which instantiates a dummy processor at each round and inserts it into the processor list.
=> Added client callbacks to adjust the processors in the runtime

configs/MNIST/fedavg_lenet5_timm_globalLR.yml, plato/trainers/basic.py
When I used the timm scheduler where the trainer type is timm_basic, I also set the config global_lr_scheduler to true and it will give out such error report: 
```
plato/trainers/basic.py", line 518, in _adjust_lr
initial_lr = global_lr_scheduler.get_last_lr()
AttributeError: 'CosineLRScheduler' object has no attribute 'get_last_lr'
```
That is because ```timm``` scheduler does not have class function ```get_last_lr``` only has private function ```_get_lr```.  
Override the ```_adjust_lr``` function in class ```TrainerWithTimmScheduler```. The update of timm scheduler is different from torch scheduler. First it has ```step``` and ```step_update```, the scheduler  will automatically decide step on epochs and step on num of updates. The parameter is epoch or num of updates, and we need to …
=> fixed bug, making timm scheduler work when setting global_scheduler: true

.gitignore, configs/ViT/fedavg_cifar10_swinv2.yml, configs/ViT/fedavg_tinyimagenet_levit.yml, docs/configuration.md, plato/models/registry.py, plato/models/vit.py
Previously, for model types hugging face, LM transformers are supported. Here, ViTs from HuggingFace are added
Added a model type in registered factories in ```plato/models/registry.py``` and added corresponding model in ```vit.py```.  In ```vit.py```, three changes are made. 
* Add resolution adjustment, the resolution of images will be automatically set to the same as required resolution as the given ViT pretrained models.
*  Extract ```logits``` from outputs of hugging face models.
*  For ViT models, on HuggingFace, many model name include ```/```, this will raise conflicts when using model name as the save path. As a result, in the document, I added requirement to replace ```/``` with ```@```  in model name. Then plato model API will handle it through ```model_name = …
```
=> Added HuggingFace ViT into model types

docs/examples.md, examples/dlg/dlg_trainer.py, examples/split_learning/split_learning.py, examples/split_learning/split_learning_MNIST_lenet5.yml, examples/split_learning/split_learning_algorithm.py, examples/split_learning/split_learning_client.py, examples/split_learning/split_learning_server.py, examples/split_learning/split_learning_trainer.py, plato/trainers/basic.py
This PR aims to reimplement the split learning example strictly following the original design, compared with the previous implementation, the following changes are made.
1. Clients communicate with the server for each iteration of training.
2. Clients sequentially interact with the server, which means only one client is selected to conduct split learning with the server until it is done when a preset round number is reached.
3. No aggregation among clients. The client-side model is implicitly synchronized through the server model, which is shared and updated by all clients.   
This has been tested by running
`
python examples/split_learning/split_learning.py -c examples/split_learning/split_learning_MNIST_lenet5.yml -l warn
`
The status of split learning is logged in the warning level, …
=> Reimplemented split learning

plato/servers/fedavg_cs.py
Fix the bug where the test set in cross-silo is none for FEMNIST (and potential future other partitioned datasets). This prevents FEMNIST testing from working in cross-silo mode
The original code uses the edge server id as argument for obtaining datasource. However, the FEMNIST object only has testing dataset when the client_id argument is 0. Thus, the original code essentially makes it impossible to perform testing on the edge servers. The change will force the edge server to obtain the datasource pretending as the global server, ensuring uniform testing across all servers. An alternative would be to change the femnist datasource file to consider edge servers (it currently does not). However, it is hard to see a use case where each edge server would want different testing data, hence the …
=> Bug fix: FEMNIST test set is None in cross-silo.

plato/trainers/loss_criterion.py, plato/trainers/lr_schedulers.py, plato/trainers/optimizers.py, tests/TestsConfig/personalized_config.yml, tests/personalization_tests.py
The ```get()``` functions of training terms, including `lr_schedulers`, `optimizers`, and `loss_criterion` are enhanced by adding `**kwargs` argument.
By doing so, these functions are expected to support customized optimizers, lr schedulers, and loss functions based on the corresponding hyper-parameters.
Apart from improving the flexibility of these functions, this enhancement enables the trainers of Plato to be applied in more scenarios, such as personalized federated learning (pFL). 
There are two stages in general personalized federated learning. The first is the normal federated training paradigm, while the second is personalization training. These two stages should utilize different lr schedulers, optimizers, and loss functions. The user expects to set the corresponding …
=> Enhanced the get() functions for the trainers of Plato

plato/models/registry.py, tests/TestsConfig/personalized_config.yml, tests/personalization_tests.py
This is a series of work related to [PR#263](https://github.com/TL-System/plato/pull/263). To be specific, following the same target and mechanism of adding `**kwargs` argument, this PR aims to enhance the ```get()``` functions of `registry.py` under `models` folder of Plato. 
Following the same motivation as [PR#263](https://github.com/TL-System/plato/pull/263), the modification purpose of this PR is to allow the ```get()``` function to support more flexible and extensive model definitions.
For example, in the personalized federated learning domain, the global model can be defined by calling `model_registry.get()` while the personalized model can be directly defined by calling 
```
model_registry.get(
model_name=Config().trainer.personalized_model_name, …
```
=> Enhanced the get() function of Plato's model register 

plato/datasources/celeba.py, plato/datasources/cifar10.py, plato/datasources/cifar100.py, plato/datasources/cinic10.py, plato/datasources/coco.py, plato/datasources/emnist.py, plato/datasources/fashion_mnist.py, plato/datasources/feature.py, plato/datasources/femnist.py, plato/datasources/flickr30k_entities.py, plato/datasources/gym.py, plato/datasources/huggingface.py, plato/datasources/kinetics.py, plato/datasources/mnist.py, plato/datasources/pascal_voc.py, plato/datasources/purchase.py, plato/datasources/qoenflx.py, plato/datasources/referitgame.py, plato/datasources/registry.py, plato/datasources/tiny_imagenet.py, plato/datasources/yolo.py
This PR added the `**kwargs` to all listed datasets of datasource and `get()` of the registry. By doing so, users can apply their custom functions to data sources.
The basic motivation is adding the specific transform when defining one dataset for subsequent learning. For example, there are three needed transforms, A, B, and C, for the CIFAR10 dataset. The 'get()' can be called three times to define the same CIFAR10 with three different transforms. 
No test is required as this change does not influence the existing Plato's examples.
=> Added **kwargs to datasource

.github/workflows/delete_workflow_runs.yml, .github/workflows/gpu_tests.yml.disabled, .github/workflows/mindspore_tests.yml, .github/workflows/pypi_publish.yml, .github/workflows/pytorch_tests.yml, .github/workflows/pytorch_yolov5_tests.yml, .github/workflows/tensorflow_tests.yml, docs/client.md, docs/server.md, docs/trainer.md, examples/callbacks/callback_examples.py, examples/callbacks/callbacks.py, plato/callbacks/client.py, plato/callbacks/server.py, plato/clients/base.py, plato/clients/simple.py, plato/servers/base.py, plato/trainers/basic.py, plato/trainers/diff_privacy.py, plato/trainers/gan.py, plato/trainers/huggingface.py, plato/trainers/mindspore/basic.py, plato/trainers/pascal_voc.py, plato/trainers/registry.py, plato/trainers/tensorflow/basic.py, plato/trainers/yolov5.py
This PR aims to improve the flexibility of callback mechanism in Plato. To customize the built-in trainers with callbacks, user needs to define a new trainer class instead of directly passing callbacks to the trainer. This is because currently callbacks can only be declared when the instances are created, and Plato creates built-in trainers with `registry.get` where user has no access.
To improve this, the following changes are made:
1. Added function `add_callbacks` to server, client and trainer, which enables adding callbacks after instances are created.
2. The trainer is not instantiated by clients until the training begins, so we further add parameter `trainer_callbacks` to client which sets up the callbacks that will be passed to trainer later.
3. Provided an example about how to …
=> Improved the flexibility of callbacks

plato/servers/base.py
In plato/servers/base.py, Heaq is pushed under all conditions, but only under certain conditions it is popped.  If it is not popped, the RAM consumption will increase as the increasing of training rounds. It could lead to RAM overflow. Therefore, an if statement is added before a heap push function, only when a heap will be popped then it will be pushed.
It has been tested with normal Fedavg and Fedavg with encryption. After the fix, RAM consumption does not increase as the training round increases.
=> Fix memory overflow issues during training. Heapq does not pop under some conditions.
